### ISSUE TITLE
Hugginface  runwayml/stable-diffusion-v1-5 not working now

### ISSUE THREAD

**Issue by rhtm02** [open-mmlab/StyleShot#26]
Hi. first thx to your nice works. really impressed!

but i have one issue running your demo.
`Traceback (most recent call last):
  File "styleshot_text_driven_demo.py", line 47, in <module>
    main(args)
  File "styleshot_text_driven_demo.py", line 19, in main
    base_model_path = snapshot_download(base_model_path, local_dir=base_model_path)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 238, in snapshot_download
    raise api_call_error
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 2588, in repo_info
    return method(
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 2373, in model_info
    hf_raise_for_status(r)
  File "/home/hjlee/anaconda3/envs/styleshot/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66d19fb2-4cecc1ab79e34c007ad62889;79c2524e-b5bb-4f16-817a-3a891177edd2)`

maybe this repo is not working now. 
so i want to get pre-trained weight for runwayml/stable-diffusion-v1-5.

thank you!

**Comment by Jeoyal** [comment]
Hi @rhtm02, thank you for your interest in our work. You can search for the keyword stable-diffusion-v1-5 to find other accessible repositories on Huggingface (e.g., [benjamin-paine/stable-diffusion-v1-5](https://huggingface.co/benjamin-paine/stable-diffusion-v1-5/tree/main)).

**Comment by rhtm02** [comment]
thx for your fast answer!
one more thing to ask you..
how much vram request this demo?
i just use style transfer using reference image.
fp16 is working?

**Comment by rhtm02** [comment]
thank you! have a nice day

**Comment by Jeoyal** [comment]
You're welcome! Hope you achieve the results you desire. :)
